# Generated by Django 3.2.5 on 2021-07-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='hobby',
            new_name='MonthlySalary',
        ),
    ]
